name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: cd auth && docker build -t 123245399203948/auth .
     - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - run: docker push 123245399203948/auth
     - uses: digitalocean/action-doctl@v2
       with:
         token: ${{ secrets.DIGITALOCEAN_ACCCESS_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save ticketing
     - run: kubectl rollout restart deployment auth-depl
     - run: docker logout
      
